### ISSUE TITLE
Add GitHub actions setup instructions

### ISSUE THREAD

**Issue by dsherret** [denoland/dnt#12]
My current way of publishing when the script lives at `./scripts/build_npm.ts` and creating tags with the format `x.x.x` (no `v` prefix):

```
- name: Get tag version
  if: startsWith(github.ref, 'refs/tags/')
  id: get_tag_version
  run: echo ::set-output name=TAG_VERSION::${GITHUB_REF/refs\/tags\//}
- uses: actions/setup-node@v2
  with:
    node-version: '16.x'
    registry-url: 'https://registry.npmjs.org'
- name: npm build
  run: deno run -A ./scripts/build_npm.ts ${{steps.get_tag_version.outputs.TAG_VERSION}}
- name: npm publish
  if: startsWith(github.ref, 'refs/tags/')
  env:
    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  run: |
    cd npm
    npm publish
```
