### ISSUE TITLE
Shims and dev dependencies are inluced in the final package

### ISSUE THREAD

**Issue by talentlessguy** [denoland/dnt#353]
I'm having a simple DNT setup and for whatever reason my GH action doesn't care about npmignore and it ends up putting all the files in the npm folder.

My `scripts/npm.ts` script:

```ts
import { build, emptyDir } from 'https://deno.land/x/dnt@0.39.0/mod.ts'

await emptyDir('./npm')

await build({
  packageManager: 'pnpm',
  entryPoints: ['./mod.ts'],
  outDir: './npm',
  scriptModule: false,
  shims: { deno: 'dev', weakRef: 'dev' },
  test: true,
  compilerOptions: {
    lib: ['DOM', 'ES2021.String'],
    target: 'ES2022',
  },
  package: {
    name: '@stauro/filebase-upload',
    version: Deno.args[0],
    description: 'Minimal library to upload files on Filebase S3 API. Partially based on AWS SDK v3.',
    license: 'Apache-2.0',
    repository: {
      type: 'git',
      url: 'git+https://github.com/stauroDEV/filebase-upload.git',
    },
    bugs: {
      url: 'https://github.com/stauroDEV/filebase-upload/issues',
    },
    devDependencies: {
      '@types/node': 'latest',
      '@types/aws4': 'latest',
    },
    files: ['esm'],
    publishConfig: {
      access: 'public',
    },
  },
  postBuild() {
    // steps to run after building and before running the tests
    Deno.copyFileSync('LICENSE', 'npm/LICENSE')
    Deno.copyFileSync('README.md', 'npm/README.md')
  },
})
```

My GH action:

```yml
name: Publish

on:
  push:
    tags:
        - '*'

env:
    FILEBASE_TOKEN: ${{ secrets.FILEBASE_TOKEN }}
          
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Get tag version
        if: startsWith(github.ref, 'refs/tags/')
        id: get_tag_version
        run: echo TAG_VERSION=${GITHUB_REF/refs\/tags\//} >> $GITHUB_OUTPUT
      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x
      - uses: actions/setup-node@v3
        with:
            node-version: '18.x'
            registry-url: 'https://registry.npmjs.org'
      - name: npm build
        run: deno run -A ./scripts/npm.ts ${{steps.get_tag_version.outputs.TAG_VERSION}}
      - name: npm publish
        if: startsWith(github.ref, 'refs/tags/')
        env:
         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: cd npm && npm publish
```

In npm files I see DNT stuff that shouldn't be there:

![image](https://github.com/denoland/dnt/assets/35937217/a55c4aef-d390-4e4b-ad65-f2d37473da6c)
